# https://d35mpxyw7m7k7g.cloudfront.net/bigdata_1/Get+Authentication+for+Google+Service+API+.pdf
client_config_backend: settings
client_config:
  client_id: 1020961993096-gj9oagu7pbn9k35ujtvqr9cebnufsbka.apps.googleusercontent.com
  client_secret: 6vh-hhL9X4PQFFUhFn7_l0jD
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
- https://www.googleapis.com/auth/drive.file